import { useState } from 'react'
import './App.css'

const navItems = [
  ['▦', 'Dashboard'], ['♙', 'User Management'], ['♙', 'Admin Management'], ['□', 'Admissions & Routing'],
  ['♢', 'Manage Programs'], ['✧', 'Talent Corner'], ['▣', 'Financial Ops'], ['▱', 'Laptops'], ['♧', 'Communities'],
  ['⟷', 'Referrals'], ['▧', 'Reports & Insights'],
]
const communities = [
  { icon: '▰', name: 'Frontend Engineering', members: '342', channels: '8' }, { icon: '▥', name: 'Data Science', members: '287', channels: '6' },
  { icon: '🎨', name: 'UX Design', members: '198', channels: '5' }, { icon: '⚙', name: 'Backend Development', members: '256', channels: '7' },
  { icon: '▥', name: 'Mobile Development', members: '145', channels: '4' },
]
const channelRows = [
  ['general', 'General discussions', '342', '1240', true], ['announcements', 'Official announcements only', '342', '45', true], ['resources', 'Share learning resources', '298', '567', true], ['help', 'Ask for help and support', '312', '892', true], ['showcase', 'Show off your projects', '256', '234', true], ['off-topic', 'Non-course related chat', '189', '456', false], ['jobs', 'Job opportunities and career', '278', '123', true], ['random', 'Random conversations', '156', '678', false],
]
const members = [
  ['J', 'John Doe', 'john@email.com', '2026-01-15', '234', 'active'], ['J', 'Jane Smith', 'jane@email.com', '2026-01-10', '567', 'active'], ['M', 'Mike Johnson', 'mike@email.com', '2026-02-01', '89', 'Suspended'], ['S', 'Sarah Wilson', 'sarah@email.com', '2026-02-15', '145', 'active'], ['D', 'David Brown', 'david@email.com', '2025-12-01', '892', 'active'],
]

function Logo() { return <div className="brand"><span className="brand-mark"><i /><b /></span><span><strong>Talent</strong><em>Conta</em></span></div> }
function Header() { return <header className="topbar"><Logo /><div className="top-actions"><span className="bell">♧</span><span className="avatar photo">S</span></div></header> }
function Sidebar() { return <aside className="sidebar"><nav>{navItems.map(([icon, label]) => <button key={label} className={label === 'Communities' ? 'active' : ''}><span>{icon}</span>{label}</button>)}</nav><button className="logout"><span>⇥</span>Logout</button></aside> }
function CommunityList({ onOpen }) { return <section className="community-list"><div className="list-heading"><h2>Communities</h2><label className="search"><span>⌕</span><input placeholder="Search communities..." /></label></div><div className="community-items">{communities.map((community, index) => <button className={`community-item ${index === 0 ? 'selected' : ''}`} key={community.name} onDoubleClick={onOpen}><span className="community-icon">{community.icon}</span><span className="community-copy"><strong>{community.name}</strong><small>♧ {community.members}　# {community.channels}</small><em>Active</em></span></button>)}</div><button className="create-button">♧ Create Communities</button></section> }
function CommunityHeader({ setTab, tab }) { return <><div className="community-header"><span className="community-icon large">▰</span><div><h1>Frontend Engineering</h1><p>342 members • 8 channels</p></div><span className="more">⋮</span></div><div className="tabs"><button className={tab === 'overview' ? 'selected' : ''} onClick={() => setTab('overview')}>∿　Overview</button><button className={tab === 'channels' ? 'selected' : ''} onClick={() => setTab('channels')}>#　Channels</button><button className={tab === 'members' ? 'selected' : ''} onClick={() => setTab('members')}>♧　Members</button></div></> }
function Overview() { const stats = [['342', 'Total Members', '+12% this month', '♧', 'green'], ['1,240', 'Messages Today', 'Active', '▢', 'blue'], ['8', 'Active Channels', 'All operational', '#', 'teal'], ['3', 'Flagged Messages', 'Needs review', '⚐', 'red']]; return <><div className="stats">{stats.map(([value, label, note, icon, color]) => <div className="stat" key={label}><div><strong>{value}</strong><span>{label}</span><em className={color}>{note}</em></div><b className={color}>{icon}</b></div>)}</div><section className="activity"><h2>Recent Activity</h2>{[['J', 'John Doe posted in #general', '2 minutes ago'], ['J', 'Jane Smith joined the Communities', '15 minutes ago'], ['M', 'Mike Johnson posted in #help', '1 hour ago'], ['S', 'Sarah Wilson reacted to a message', '2 hours ago']].map(([initial, text, time]) => <div className="activity-row" key={text}><span className="avatar">{initial}</span><div><strong>{text}</strong><small>{time}</small></div></div>)}</section></> }
function Channels() { return <><div className="section-title"><h2>Channel Management</h2><button className="primary">#　Create Channel</button></div><div className="table channel-table"><div className="table-head"><span>CHANNEL</span><span>MEMBERS</span><span>MESSAGES</span><span>STATUS</span><span>ACTIONS</span></div>{channelRows.map(([name, description, memberCount, messageCount, active]) => <div className="table-row" key={name}><div><strong>#　{name}</strong><small>{description}</small></div><span>{memberCount}</span><span>{messageCount}</span><span className={`status ${active ? '' : 'inactive'}`}>{active ? 'Active' : 'Inactive'}</span><b>⋮</b></div>)}</div></> }
function Members() { return <><div className="section-title members-title"><h2>Communities Members</h2><div className="member-filters"><label className="search"><span>⌕</span><input placeholder="Search members..." /></label><button className="select">All Statuses　⌄</button></div></div><MemberTable /><div className="pending"><span>Pending Reviews</span></div><div className="table review-table"><div className="table-head"><span>MEMBER</span><span>REQUEST SENT</span><span>PROGRAM</span><span>ACTIONS</span></div>{members.map(([initial, name, email, date]) => <div className="table-row" key={`review-${name}`}><div><span className="avatar">{initial}</span><span><strong>{name}</strong><small>{email}</small></span></div><span>{date}</span><span>Mobile Dev &amp; UI/UX</span><span className="review-actions">ⓧ Reject　<span>ⓥ Approve</span></span></div>)}</div></> }
function MemberTable() { return <div className="table member-table"><div className="table-head"><span>MEMBER</span><span>JOIN DATE</span><span>MESSAGES</span><span>STATUS</span><span>ACTIONS</span></div>{members.map(([initial, name, email, date, messages, status]) => <div className="table-row" key={name}><div><span className="avatar">{initial}</span><span><strong>{name}</strong><small>{email}</small></span></div><span>{date}</span><span>{messages}</span><span className={`status ${status === 'active' ? '' : 'suspended'}`}>{status}</span><button className="manage">Manage</button></div>)}</div> }
function DetailView({ onBack }) { const posts = [['AT', 'Admin Team', '2 hours ago', 'Welcome to TalentCona Community! 🎉 This is your space to connect, learn, and grow together. Please read our community guidelines and introduce yourself!', '12 replies'], ['SC', 'Sarah Chen', '1 hour ago', 'Quick tip for Front-End Development Program beginners: Always use the key prop when rendering lists! It helps Front-End Development Program identify which items have changed.', '6 replies'], ['MR', 'Michael Rodriguez', '45 min ago', 'Just completed my first full-stack project! Thanks to everyone who helped me along the way. The mentorship here is incredible! 🔥', '8 replies'], ['EJ', 'Emily Johnson', '30 min ago', "Does anyone have recommendations for CSS Grid resources? I'm struggling with the gallery layout assignment. Any help would be appreciated! 🙏", '4 replies'], ['DK', 'David Kim', '15 min ago', "Pro tip: Use Front-End Development Program DevTools to debug your components. It's a game changer for understanding component state and props!", '3 replies']]; return <div className="detail-page"><button className="back" onClick={onBack}>← Back</button><section className="detail-card"><div className="detail-intro"><span className="program-icon">⚛</span><div><h1>Front-End Development Program Developers Hub</h1><p>A community for Front-End Development Program developers to share knowledge, best practices, and latest updates</p><small>♧ 15,420 members　 <b>Programming</b></small></div></div><div className="detail-body"><aside className="channel-nav"><small>CHANNELS</small>{['general', 'announcements', 'help-support', 'showcase', 'resources', 'off-topic'].map((channel, index) => <button className={index === 0 ? 'active' : ''} key={channel}>#　{channel}{index === 1 && <i>2</i>}{index === 2 && <i>5</i>}</button>)}</aside><div className="conversation"><div className="conversation-head"><strong>#　general</strong><span>•　General community discussions</span><b>⌕</b></div><div className="posts">{posts.map(([initial, name, time, content, replies], index) => <article className="post" key={name}><span className="avatar">{initial}</span><div><header><strong>{name}</strong><small>{time}</small></header><p>{index === 0 && <em>⚒　Pinned by you</em>}{content}</p><div className="reactions">♡　{index + 5}　 ◉　 {index + 6}　 ◌</div><a>◯　{replies}</a></div><b>⋮</b></article>)}</div><div className="message-box"><span className="avatar">YO</span><input placeholder="Message #general" /><span>♧　☺　<button>➤</button></span></div></div></div></section></div> }
function App() { const [tab, setTab] = useState('overview'); const [detail, setDetail] = useState(false); if (detail) return <><Header /><Sidebar /><DetailView onBack={() => setDetail(false)} /></>; return <><Header /><Sidebar /><main className="workspace"><CommunityList onOpen={() => setDetail(true)} /><section className="content"><CommunityHeader setTab={setTab} tab={tab} />{tab === 'overview' && <Overview />}{tab === 'channels' && <Channels />}{tab === 'members' && <Members />}</section></main></> }
export default App
